language: python

python:
  - "3.7"

env:
  - DOCKER_COMPOSE_VERSION=1.25.0 RUNS=10 SERVICE=<service name> VULNS=<vulns number>

  - DOCKER_COMPOSE_VERSION=1.25.0 RUNS=20 SERVICE=all

  - DOCKER_COMPOSE_VERSION=1.25.0 RUNS=200 SERVICE=<service name> VULNS=<vulns number>

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip python3-dev git libssl-dev libffi-dev build-essential
  - pip install -r checkers/requirements.txt
  - export SERVICES="$(ls services | xargs)"
  - 'echo "Found services: $SERVICES"'
  - ./start.sh "$SERVICE"

before_script:
  - sleep 60

script:
  - ./check.sh "$SERVICE"

after_script:
  - ./stop.sh

after_failure:
  - ./logs.sh
